language: android

script:
  - "chmod +x ./gradlew"
  - "./gradlew assembleRelease"

android:
  components:
    - build-tools-29.0.3

    # The SDK version used to compile your project
    - android-29

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository
